### ISSUE TITLE
Security Auth Failure: make sure python is signed with codesign util

### ISSUE THREAD

**Issue by jdamata** [jdamata/k8vault#3]
keyring.errors.KeyringError: Can't get password from keychain: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')

**Comment by jdamata** [comment]
Resolved by:

1. go to Keychain Access app in the Utilities folder
2. under the File menu, choose *Lock Keychain "Login"*
3. go to the File menu again and choose *Unlock Keychain "Login"*

but why

**Comment by superlitian** [comment]
No, this is a not good idea , my app now can't get cookies.
